/* =========================
   BRAWLER INFO (strategy write-ups)
========================= */
const brawlerInfo = {
    "8bit": ["Use long-range pressure and destroy the turret when possible."],
    "alli": ["Use slows to reduce her attack range and make approaching more difficult. Open areas also limit her ability to approach safely."],
    "amber": ["Use long-range pressure, wall-peeking and aggressive approaches to prevent safe use of her attack."],
    "angelo": ["Pressure from range and use cover or spawned objects to disrupt charged attacks. Do not give a safe lane for repeated shots."],
    "ash": ["Use long-range pressure and crowd control before Rage becomes high. Prevent him from reaching close range with high Rage."],
    "barley": [""],
    "bea": ["Use spawned objects and area attacks to give her additional targets. Long-range pressure can also make her attacks harder to land."],
    "belle": ["Use cover and attacks from multiple directions to limit her long-range control."],
    "berry": [""],
    "bibi": ["Use knockback and other crowd control to interrupt her approach and prevent her from isolating targets."],
    "bo": ["Pressure before he can safely set up mines and use unpredictable paths when approaching. Do not give the mines control over the main route."],
    "bolt": ["Use slows, roots, knockbacks and other crowd control to interrupt his movement. Avoid unnecessary wallbreak and spread out to reduce Super charge."],
    "bonnie": [""],
    "brock": ["Close the distance and force constant repositioning to make his attacks harder to land."],
    "bull": ["Interrupt the Super with crowd control whenever possible. Stopping the charge removes his main way of engaging."],
    "buster": ["Use strong close-range damage that can survive the initial pressure and win the direct fight."],
    "buzz": ["Prevent a clean Super engage with unpredictable movement and crowd control."],
    "byron": ["Pressure from range, use cover and apply anti-heal to limit his ability to cycle damage and healing."],
    "carl": ["Interrupt the Super with crowd control or defensive abilities whenever possible."],
    "charlie": ["Pressure from the appropriate range and use map geometry to limit Cocoon opportunities."],
    "chester": [""],
    "chuck": [""],
    "clancy": ["Pressure early and limit access to easy targets so he cannot gain levels safely. Spawned objects can also reduce the value of his attacks."],
    "colette": [""],
    "colt": ["Use unpredictable movement to make his attacks harder to land and punish him during reloads."],
    "cord": ["Maintain distance and use slows or other crowd control to prevent a clean close-range engage."],
    "crow": ["Use extra targets, long-range pressure and anti-heal to reduce chip damage and limit isolated targets."],
    "damian": ["Use silence, crowd control and constant pressure to interrupt abilities and long attack sequences."],
    "darryl": [""],
    "doug": ["Use anti-heal and long-range pressure, then separate him from teammates before committing."],
    "draco": ["Interrupt the Super with stuns, freezes or other reliable crowd control before momentum builds."],
    "dyna": ["Close the distance quickly and use mobility or wallbreak to reduce safe positions."],
    "edgar": ["Maintain enough distance to force movement resources before the engage, then use knockback or crowd control when he commits."],
    "emz": ["Approach from unexpected angles and use mobility to fight outside her ideal attack range."],
    "eve": ["Use area damage and multi-target attacks to clear Hatchlings efficiently and prevent them from protecting her."],
    "fang": ["Interrupt the Super chain with crowd control, high burst damage or extra targets."],
    "finx": ["Close the distance before abilities can be used safely. Limited defensive options make direct pressure effective."],
    "frank": ["Maintain distance, interrupt charged attacks and punish committed engages."],
    "gale": ["Maintain enough range to avoid close-range control while using mobility to dodge attacks. Removing cover can also help."],
    "gene": ["Use spawned objects to force ammunition onto additional targets and take advantage of the slow reload."],
    "gigi": ["Force ammunition to be spent before engaging, then attack while fewer defensive options are available."],
    "glowbert": ["Break the tether with walls or forced repositioning. Anti-heal and constant pressure reduce the value of his healing."],
    "gray": ["Pressure directly and use mobility to prevent safe portal setups. Additional targets can also interfere with his attacks."],
    "griff": ["Stay outside the range where his full attack connects and punish missed ammunition during reload."],
    "grom": ["Close the distance after attacks are spent. Low ammunition makes close-range pressure especially effective."],
    "gus": ["Use close-range pressure or attacks around cover to limit safe ranged positioning."],
    "hank": ["Interrupt the bubble charge with crowd control and use long-range pressure when crossing open areas."],
    "jacky": ["Maintain distance and use knockback or crowd control to prevent sustained close-range contact."],
    "jaeyong": [""],
    "janet": ["Pressure before Super is charged and force close-range fights to limit long-range lane control."],
    "jessie": ["Spread out to prevent attack chains and destroy the turret before it becomes a constant source of pressure."],
    "juju": ["Pressure quickly before terrain-based attack options can be prepared. Close-range engagements reduce setup time."],
    "kenji": ["Use high burst and strong close-range damage to stop the approach. Avoid relying on low damage that can be recovered from."],
    "kaze": [""],
    "kit": ["Interrupt the Super sequence with silence, stuns, knockbacks or other crowd control."],
    "larry": ["Close the distance and use mobility to prevent long-range attacks from controlling the lane."],
    "leon": ["Use extra targets, vision and crowd control to prevent isolated burst opportunities."],
    "lily": ["Use extra targets, crowd control and high durability to prevent surprise engages from securing an easy kill."],
    "lola": ["Force the Ego away or destroy it before committing to a fight. Avoid fighting inside its attack range."],
    "lou": [""],
    "lumi": ["Use long-range pressure and mobility to force repeated repositioning and prevent comfortable lane control."],
    "maisie": ["Use unpredictable movement to make her shots harder to land. Respect the close-range Super when approaching."],
    "mandy": ["Use cover and constant repositioning to prevent comfortable long-range shots."],
    "max": [""],
    "meg": ["Maintain range and force an approach through open space. Consistent ranged pressure is safer than direct close-range fights."],
    "melodie": [""],
    "meeple": ["Use mobility, close-range pressure and extra targets to disrupt the attack pattern."],
    "mico": ["Use crowd control, high durability and spawned targets to survive the attack cycle and punish the landing."],
    "mina": ["Use knockback, mobility and crowd control to interrupt the close-range attack sequence."],
    "moe": [""],
    "mortis": ["Prevent isolated targets and free dash chains. Keep defensive abilities available for the engage and punish overextension."],
    "mrp": ["Destroy or bypass the porter station and pressure directly instead of repeatedly fighting spawned porters."],
    "najia": ["Use extra targets and constant pressure to disrupt the main attack instead of relying only on range."],
    "nani": ["Use unpredictable movement and avoid straight-line paths. Her main threat comes from landing multiple projectiles together."],
    "nita": ["Deal with both targets efficiently and remove the cover used for approaches. Maintain enough range to limit close-range pressure."],
    "nori": ["There is not enough reliable matchup information to provide a specific strategy."],
    "ollie": ["Prevent the main ability from controlling the fight with durable targets and crowd control."],
    "otis": ["There is not enough reliable current matchup information to provide a specific strategy."],
    "pam": ["Maintain range and force movement away from the healing station. Destroy it before committing when possible."],
    "pearl": ["Apply constant pressure to prevent comfortable heat management and setup."],
    "penny": ["Close the distance and bait the barrel before committing to reduce defensive options."],
    "pierce": ["Spread out and use disposable targets to prevent easy multi-target attacks and waste ammunition."],
    "piper": ["Use cover, unpredictable movement and aggressive approaches to prevent maximum-range attacks."],
    "poco": ["Use anti-heal and sustained pressure to reduce healing value. Force Super to be used defensively."],
    "primo": ["Maintain range and use mobility, knockback or sustained ranged damage to prevent melee access."],
    "rt": ["Use cover-based pressure and unfavorable angles to limit long-range attacks."],
    "rico": ["Use wallbreak or attacks that bypass cover. Avoid narrow areas where wall bounces provide maximum value."],
    "rosa": ["Maintain range and force an approach through open space. Use consistent ranged pressure instead of direct close-range fights."],
    "ruffs": ["There is not enough reliable matchup information to provide a specific strategy."],
    "sam": ["Use range, knockback and movement control to prevent repeated close-range access and collection of the knuckle-busters."],
    "sandy": ["Use scouting and area control to prevent the Super from creating a safe approach."],
    "shade": ["Remove or bypass walls and avoid giving unnecessary Super charge. Open areas make the matchup easier."],
    "shelly": ["Maintain range and force Super to be used defensively. Do not commit to close-range fights while full burst is available."],
    "sirius": ["Pressure directly instead of relying on stationary defenses that can be destroyed safely from range."],
    "spike": ["Maintain range and prevent easy value from Super or the healing plant. Use consistent ranged pressure and area control."],
    "sprout": ["Bypass walls or attack from angles that cannot be defended easily. Prevent safe terrain control."],
    "squeak": ["Close the distance before zoning is established. Slow projectiles make aggressive movement especially effective."],
    "starrnova": ["Pressure before Super can safely control the fight. Use durable targets and timed aggression to survive the initial pressure."],
    "stu": ["Use extra targets, crowd control and high durability to limit free dashes and force mobility to be used defensively."],
    "surge": ["Prevent early upgrades by applying pressure before stronger stages are reached. Limit Super and upgrade value."],
    "tara": ["Spread out to limit Super value and use piercing attacks to reduce the effectiveness of spawned shadows."],
    "tick": ["Close the distance before defensive abilities can be cycled. Mobility is especially effective once those tools are unavailable."],
    "trunk": ["Maintain range and apply constant chip damage while approaching. Do not allow a comfortable close-range fight."],
    "wendy": [""],
    "willow": ["Pressure from outside the preferred range or close the distance before Super is charged. Wallbreak can also expose safe positions."],
    "ziggy": ["Close the distance or remove walls to reduce area control. Mobility makes direct pressure easier."]
};
