/* =========================
   BRAWLER TAGS (kit traits)
   Small badge icons shown on each brawler's portrait (top-right corner,
   where the class indicator used to sit). A brawler can have zero, one,
   or several tags.

   IMPORTANT: this is a best-effort STARTING DRAFT, not a verified list.
   Brawl Stars kits change with balance updates and there are 100+
   brawlers here, so treat blank entries as "not yet reviewed" rather
   than "confirmed no tag." Same pattern as brawler-main.js — just edit
   the array for a brawler to add/remove a tag.
========================= */

const tagEmoji = {
    knockback: "💨",
	stun: "😵",
    wallbreak: "🔨",
    pierce: "🏹",
    spawnable: "👾",
    poison: "☣️",
    heal: "💖",
    invisibility: "👻",
    antiheal: "🩸",
    pull: "🧲",
	water: "🌊"
};

const tagLabel = {
    knockback: "Knockback",
	stun: "Stun",
    wallbreak: "Wallbreak",
    pierce: "Pierce",
    spawnable: "Spawnable",
    poison: "Poison",
    heal: "Heal",
    invisibility: "Invisibility",
    antiheal: "Anti-Heal",
    pull: "Pull",
	water: "Water-walking"
};

const brawlerTags = {
    "8bit": ["spawnable"],
    "alli": ["heal", "invisibility", "water","pierce"],
    "amber": ["poison","pierce"],
    "angelo": ["heal", "pierce", "poison", "water"],
    "ash": ["heal", "spawnable"],
    "barley": ["heal", "poison"],
    "bea": [],
    "belle": ["pierce"],
    "berry": ["heal", "knockback"],
    "bibi": ["knockback"],
    "bo": ["wallbreak"],
    "bolt": ["knockback", "wallbreak"],
    "bonnie": ["knockback"],
    "brock": ["knockback", "wallbreak"],
    "bull": ["heal", "wallbreak", "pierce", "knockback"],
    "buster": ["heal", "pull"],
    "buzz": [],
    "byron": ["heal", "antiheal", "pierce"],
    "carl": ["pierce"],
    "charlie": ["spawnable"],
    "chester": ["wallbreak", "knockback"],
    "chuck": ["spawnable"],
    "clancy": [],
    "colette": [],
    "colt": ["wallbreak"],
    "cord": ["pull"],
    "crow": ["poison", "antiheal"],
    "damian": ["heal", "knockback", "spawnable"],
    "darryl": ["knockback"],
    "doug": ["heal"],
    "draco": [],
    "edgar": ["heal"],
    "emz": ["knockback"],
    "eve": ["spawnable"],
    "fang": [],
    "finx": [],
    "frank": ["knockback", "wallbreak"],
    "gale": ["knockback"],
    "gene": ["heal", "pull", "wallbreak"],
    "gigi": ["invisibility"],
    "glowbert": ["heal"],
    "gray": ["spawnable", "wallbreak"],
    "griff": ["heal", "knockback", "wallbreak"],
    "grom": ["knockback", "pierce", "wallbreak"],
    "gus": ["heal", "spawnable"],
    "hank": ["knockback"],
    "jacky": [],
    "jaeyong": ["heal", "pierce"],
    "janet": [],
    "jessie": ["spawnable"],
    "juju": ["invisibility", "spawnable", "water"],
    "kenji": [],
    "kaze": ["heal", "invisibility"],
    "kit": ["heal", "invisibility"],
    "larry": ["spawnable"],
    "leon": ["invisibility", "spawnable"],
    "lily": [],
    "lola": ["spawnable"],
    "lou": [],
    "lumi": [],
    "maisie": ["knockback"],
    "mandy": ["pierce"],
    "max": [],
    "meg": ["heal"],
    "melodie": [],
    "meeple": ["knockback"],
    "mico": ["knockback"],
    "mina": [],
    "moe": ["knockback", "pierce"],
    "mortis": [],
    "mrp": ["spawnable"],
    "najia": ["poison", "spawnable"],
    "nani": ["wallbreak"],
    "nita": ["heal", "spawnable"],
    "nori": ["heal"],
    "ollie": [],
    "otis": [],
    "pam": ["heal", "spawnable"],
    "pearl": ["wallbreak"],
    "pierce": [],
    "piper": ["wallbreak"],
    "poco": ["heal"],
    "primo": ["knockback", "wallbreak"],
    "rt": [],
    "rico": ["spawnable"],
    "rosa": ["pierce"],
    "ruffs": ["spawnable", "wallbreak"],
    "sam": [],
    "sandy": [],
    "shade": [],
    "shelly": ["knockback", "wallbreak"],
    "sirius": ["spawnable"],
    "spike": ["heal", "spawnable"],
    "sprout": ["spawnable"],
    "squeak": [],
    "starrnova": [],
    "stu": ["wallbreak"],
    "surge": ["knockback"],
    "tara": ["pierce", "pull", "spawnable", "wallbreak"],
    "tick": ["wallbreak"],
    "trunk": [],
    "wendy": ["antiheal", "spawnable", "water"],
    "willow": ["poison"],
    "ziggy": []
};
