/* =========================
   BRAWLERS
========================= */
const data = {
    "8bit": { img:"images/8bit.webp", main:["penny"], alt:["belle","dyna","squeak","mandy","piper"] },
    "alli": { img:"images/alli.webp", main:["bull","buzz"], alt:["draco","rt","doug","ash"] },
    "amber": { img:"images/amber.webp", main:["byron"], alt:["belle","mortis","leon","poco","sprout","bonnie","piper","pam"] },
    "angelo": { img:"images/angelo.webp", main:["eve"], alt:["kit","piper","nani","max","jaeyong"] },
    "ash": { img:"images/ash.webp", main:["frank"], alt:["emz","gale","janet","bull"] },
    "barley": { img:"images/barley.webp", main:["tick"], alt:["mortis","brock","edgar","kenji","kaze","mico"] },
    "bea": { img:"images/bea.webp", main:["charlie"], alt:["tick","sprout","grom","mrp","byron","mandy"] },
    "belle": { img:"images/belle.webp", main:["piper"], alt:["meg","leon","mandy","byron","kit","lily"] },
    "berry": { img:"images/berry.webp", main:["kaze","crow"], alt:["barley","stu","kenji","kit","mortis"] },
    "bibi": { img:"images/bibi.webp", main:["mortis","jacky"], alt:["stu","surge","griff","cord","primo","tara","bull"] },
    "bo": { img:"images/bo.webp", main:["max"], alt:["piper","colt","stu","mico","mrp"] },
    "bolt": { img:"images/bolt.webp", main:[], alt:[] },
    "bonnie": { img:"images/bonnie.webp", main:["charlie"], alt:["colette","bea","pam","piper","rt","gus","tara"] },
    "brock": { img:"images/brock.webp", main:["piper","rt"], alt:["max","darryl","mortis","mandy","nani","kaze"] },
    "bull": { img:"images/bull.webp", main:["charlie","griff"], alt:["shelly","emz","gale","cord","mina","otis","nita"] },
    "buster": { img:"images/buster.webp", main:["bull"], alt:["mina","rt","ash","darryl","belle"] },
    "buzz": { img:"images/buzz.webp", main:["charlie","griff"], alt:["stu","max","sandy","mina","cord","bull","surge","bibi","frank","ash"] },
    "byron": { img:"images/byron.webp", main:["piper"], alt:["crow","bea","ash"] },
    "carl": { img:"images/carl.webp", main:["buzz","jacky"], alt:["surge","colette","stu","mina","bull","cord","bibi"] },
    "charlie": { img:"images/charlie.webp", main:["amber","sandy"], alt:["janet","juju"] },
    "chester": { img:"images/chester.webp", main:["pearl"], alt:["amber","charlie","lumi","mina","stu"] },
    "chuck": { img:"images/chuck.webp", main:["charlie","crow"], alt:["cord","mina","bull","kaze"] },
    "clancy": { img:"images/clancy.webp", main:["mrp"], alt:["charlie","tara","bea","piper","byron"] },
    "colette": { img:"images/colette.webp", main:["tick"], alt:["griff","bea","poco","charlie","belle","gus","lumi"] },
    "colt": { img:"images/colt.webp", main:["buster"], alt:["darryl","mortis","spike","piper","bonnie","belle","gus","byron"] },
    "cord": { img:"images/cord.webp", main:["charlie"], alt:["mina","frank","sandy","buster","surge","gale","nita"] },
    "crow": { img:"images/crow.webp", main:["piper","charlie"], alt:["janet","spike","lola","bea","pearl","hank"] },
    "damian": { img:"images/damian.webp", main:[], alt:[] },
    "darryl": { img:"images/darryl.webp", main:["lou"], alt:["surge","bea","ruffs","mina","cord","shelly","griff","rt"] },
    "doug": { img:"images/doug.webp", main:["crow"], alt:["cord","lumi","bea","griff","frank","lily"] },
    "draco": { img:"images/draco.webp", main:["lumi","amber","pam"], alt:["lou","mina","cord","frank","ash","kit"] },
    "dyna": { img:"images/dyna.webp", main:["mortis","bibi"], alt:["stu","kenji","mico","kit","kaze","hank"] },
    "edgar": { img:"images/edgar.webp", main:["gale"], alt:["otis","stu","shelly","hank","bull","doug","jacky","cord","poco"] },
    "primo": { img:"images/primo.webp", main:["stu"], alt:["surge","colette","gale","cord","mina","griff","shelly","charlie"] },
    "emz": { img:"images/emz.webp", main:["mortis","stu"], alt:["crow","janet","bonnie","amber"] },
    "eve": { img:"images/eve.webp", main:["alli"], alt:["carl","janet","poco"] },
    "fang": { img:"images/fang.webp", main:["charlie","otis"], alt:["gale","gene","eve","rt","chester","tara","draco"] },
    "finx": { img:"images/finx.webp", main:["emz"], alt:["meeple","kenji","rosa","bull","shade","bibi","mortis","larry"] },
    "frank": { img:"images/frank.webp", main:["colette"], alt:["surge","primo","charlie","chester","lou","sandy"] },
    "gale": { img:"images/gale.webp", main:["mico","buzz"], alt:["spike","piper","belle","amber","janet","larry","juju","cord"] },
    "gene": { img:"images/gene.webp", main:["8bit"], alt:["mrp","eve","penny","charlie","tara","belle"] },
    "gigi": { img:"images/gigi.webp", main:["shelly"], alt:["fang","otis","cord","edgar"] },
    "glowbert": { img:"images/glowbert.webp", main:["crow"], alt:["kenji","belle","jessie"] },
    "gray": { img:"images/gray.webp", main:["gene","tick"], alt:["mortis","leon","crow","fang","max"] },
    "griff": { img:"images/griff.webp", main:[], alt:["crow","spike","bea","janet","stu","mina"] },
    "grom": { img:"images/grom.webp", main:["lily","mico"], alt:["mortis","fang","darryl","kenji","kit","kaze"] },
    "gus": { img:"images/gus.webp", main:["charlie","bo"], alt:["byron","mandy","piper","eve","darryl","janet","8bit"] },
    "hank": { img:"images/hank.webp", main:["willow","larry","frank"], alt:["dyna","mina","bull","draco","bibi"] },
    "jacky": { img:"images/jacky.webp", main:["griff","emz","crow","otis"], alt:["shelly","surge","gale","frank","bull","primo","draco"] },
    "jaeyong": { img:"images/jaeyong.webp", main:["griff","bo","charlie","crow"], alt:["kenji"] },
    "janet": { img:"images/janet.webp", main:["kenji"], alt:["griff","bonnie","amber","carl","frank","darryl","gus"] },
    "jessie": { img:"images/jessie.webp", main:[], alt:["piper","barley","larry","squeak"] },
    "juju": { img:"images/juju.webp", main:["barley","kaze","shade"], alt:["frank","brock","cord","kit","tick"] },
    "kenji": { img:"images/kenji.webp", main:["pam"], alt:["bull","frank","draco","cord","mina","lou","meeple","jaeyong","hank"] },
    "kaze": { img:"images/kaze.webp", main:["crow"], alt:["bull","rt","otis","griff","stu"] },
    "kit": { img:"images/kit.webp", main:["cord","rt"], alt:["frank","hank","ollie","lily","draco"] },
    "larry": { img:"images/larry.webp", main:["mico","edgar"], alt:["mortis","kenji","willow"] },
    "leon": { img:"images/leon.webp", main:["crow","pearl"], alt:["gene","pam","jaeyong","mina","janet","charlie"] },
    "lily": { img:"images/lily.webp", main:["buzz"], alt:["cord","bull","draco","rt","pearl","8bit","doug"] },
    "lola": { img:"images/lola.webp", main:["belle"], alt:["bo","penny","amber","carl","lumi"] },
    "lou": { img:"images/lou.webp", main:["hank"], alt:["janet","carl","max","poco","gus","byron","bea","kenji"] },
    "lumi": { img:"images/lumi.webp", main:["amber","draco"], alt:["piper","mandy","belle","gene","lola"] },
    "maisie": { img:"images/maisie.webp", main:["stu"], alt:["charlie","mina","larry","juju"] },
	"mandy": { img:"images/mandy.webp", main:[""], alt:[""] },
    "max": { img:"images/max.webp", main:["crow"], alt:["lola","poco","gus","jaeyong"] },
    "meg": { img:"images/meg.webp", main:["draco"], alt:["spike","bea","lola","buster"] },
    "melodie": { img:"images/melodie.webp", main:["amber"], alt:["buzz","draco","crow","belle"] },
    "meeple": { img:"images/meeple.webp", main:["max"], alt:["kenji","mortis","mico","frank","bull","mrp","penny"] },
    "mico": { img:"images/mico.webp", main:["gale","buzz"], alt:["mortis","fang","darryl","kenji","kit","kaze","edgar"] },
    "mina": { img:"images/mina.webp", main:["bull","frank"], alt:["cord","surge","griff","buster","ash","jacky"] },
    "moe": { img:"images/moe.webp", main:["spike"], alt:["sprout","tick","grom","barley","willow"] },
    "mortis": { img:"images/mortis.webp", main:["jacky"], alt:["stu","shelly","otis","bull","mina","griff","chester"] },
    "mrp": { img:"images/mrp.webp", main:["kit","sprout"], alt:["janet","amber","carl","darryl","edgar","kenji","kaze"] },
    "najia": { img:"images/najia.webp", main:["byron"], alt:["kenji","mortis","poco","bibi"] },
    "nani": { img:"images/nani.webp", main:["gene"], alt:["leon","tick","max","sprout","darryl"] },
    "nita": { img:"images/nita.webp", main:["barley"], alt:["carl","griff","amber","cord","sandy"] },
    "nori": { img:"images/nori.webp", main:[], alt:[] },
    "ollie": { img:"images/ollie.webp", main:["poco"], alt:["maisie","surge","griff","lou","colette"] },
    "otis": { img:"images/otis.webp", main:["juju","larry"], alt:["piper","byron","tick","amber","janet","stu"] },
    "pam": { img:"images/pam.webp", main:["crow"], alt:["squeak","spike","lou","8bit","charlie","draco","amber","stu"] },
    "pearl": { img:"images/pearl.webp", main:["chester","leon"], alt:["amber","crow","spike","lola","meg"] },
    "penny": { img:"images/penny.webp", main:["belle"], alt:["grom","amber","squeak","juju","larry","kenji"] },
    "pierce": { img:"images/pierce.webp", main:["ruffs"], alt:["mortis","charlie","tara","spike"] },
    "piper": { img:"images/piper.webp", main:["nani"], alt:["max","leon","tick","gene","kit","kaze"] },
    "poco": { img:"images/poco.webp", main:["sam","crow"], alt:["griff","mortis","emz","kit","kaze","kenji","lou","edgar"] },
    "rt": { img:"images/rt.webp", main:["piper","brock"], alt:["max","leon","mortis","darryl","crow"] },
    "rico": { img:"images/rico.webp", main:["brock","ruffs"], alt:["sprout","grom","buzz","stu","dyna","larry"] },
    "rosa": { img:"images/rosa.webp", main:["shelly"], alt:["gale","frank","primo","bull","amber"] },
    "ruffs": { img:"images/ruffs.webp", main:["buzz"], alt:["sprout","carl","belle"] },
    "sam": { img:"images/sam.webp", main:["gale","griff"], alt:["surge","cord","charlie","nita","janet","draco","stu"] },
    "sandy": { img:"images/sandy.webp", main:["crow","nita"], alt:["gene","poco","cord"] },
    "shade": { img:"images/shade.webp", main:["frank","jacky","doug"], alt:["lou","bull","hank","trunk","brock"] },
    "shelly": { img:"images/shelly.webp", main:["chester","cord"], alt:["stu","crow","emz","tara","nita","amber"] },
    "sirius": { img:"images/sirius.webp", main:["buzz","penny"], alt:["mortis","pierce"] },
    "spike": { img:"images/spike.webp", main:["moe"], alt:["sprout","tick","grom","carl","piper","larry","juju"] },
    "sprout": { img:"images/sprout.webp", main:["mico","tick"], alt:["mortis","darryl","buzz","kaze","kenji","edgar"] },
    "squeak": { img:"images/squeak.webp", main:["darryl","kenji"], alt:["mortis","max","leon","buzz","kaze"] },
    "starrnova": { img:"images/starrnova.webp", main:[], alt:[] },
    "stu": { img:"images/stu.webp", main:["charlie","amber"], alt:["crow","lola","poco","ruffs","tara","pam","sam"] },
    "surge": { img:"images/surge.webp", main:["mrp"], alt:["ruffs","spike","eve","tara","charlie","larry","juju"] },
    "tara": { img:"images/tara.webp", main:["willow"], alt:["emz","janet","poco","amber","sandy","juju","larry"] },
    "tick": { img:"images/tick.webp", main:["mandy"], alt:["gene","fang","sam","kenji","kit","mortis","kaze","darryl"] },
    "trunk": { img:"images/trunk.webp", main:["lou"], alt:["spike","amber","maisie"] },
    "willow": { img:"images/willow.webp", main:["tick"], alt:["barley","larry","juju","stu","buzz"] },
    "ziggy": { img:"images/ziggy.webp", main:["stu"], alt:["mortis","gray","bibi","tick","hank"] }
};

/* =========================
   CLASSES
========================= */
const brawlerClass = {
    "barley":"thrower","dyna":"thrower","larry":"thrower","tick":"thrower","sprout":"thrower","grom":"thrower","ziggy":"thrower","sirius":"thrower","juju":"thrower","willow":"thrower","berry":"thrower",

    "trunk":"tank","draco":"tank","frank":"tank","fang":"tank","buster":"tank","primo":"tank","hank":"tank","jacky":"tank","rosa":"tank","ash":"tank","damian":"tank",

    "bull":"assassin","bibi":"assassin","ollie":"assassin","kenji":"assassin","mortis":"assassin","shade":"assassin","mina":"assassin","buzz":"assassin","alli":"assassin","carl":"assassin","edgar":"assassin","kaze":"assassin","lily":"assassin","mico":"assassin","sam":"assassin","chuck":"assassin","gigi":"assassin","melodie":"assassin","darryl":"assassin","bolt":"assassin","nori":"assassin","starrnova":"assassin",

    "chester":"antitank","nita":"antitank","moe":"antitank","rico":"antitank","tara":"antitank","emz":"antitank","lou":"antitank","finx":"antitank","ruffs":"antitank","sandy":"antitank","otis":"antitank","lumi":"antitank","shelly":"antitank","surge":"antitank","charlie":"antitank","gale":"antitank","spike":"antitank","cord":"antitank","maisie":"antitank","colt":"antitank","griff":"antitank","crow":"antitank","8bit":"antitank","clancy":"antitank","colette":"antitank","meg":"antitank",

    "kit":"support","max":"support","gray":"support","poco":"support","jaeyong":"support","doug":"support","glowbert":"support",

    "mandy":"sniper","rt":"sniper","gus":"sniper","piper":"sniper","brock":"sniper","byron":"sniper","angelo":"sniper","pierce":"sniper","nani":"sniper","belle":"sniper","bea":"sniper",

    "amber":"control","meeple":"control","leon":"control","pam":"control","bo":"control","pearl":"control","gene":"control","stu":"control","janet":"control","penny":"control","jessie":"control","squeak":"control","eve":"control","lola":"control","najia":"control","bonnie":"control","mrp":"control"
};

/* =========================
   CLASS ORDER
========================= */
const classOrder = [
    "antitank",
    "sniper",
    "assassin",
    "thrower",
    "tank",
    "control",
    "support"
];