/* =========================
   BRAWLERS COUNTERS
========================= */
const data = {
    "8bit": { img:"images/8bit.webp", main:["penny","belle","dyna","squeak","mandy","piper","brock","byron","pierce","barley","sprout","colette"], info:[""] },
    "alli": { img:"images/alli.webp", main:["bull","buzz","draco","rt","doug","ash"], info:[""] },
    "amber": { img:"images/amber.webp", main:["byron","belle","mortis","leon","poco","sprout","bonnie","piper","pam"], info:[""] },
    "angelo": { img:"images/angelo.webp", main:["eve","kit","piper","nani","max","jaeyong"], info:[""] },
    "ash": { img:"images/ash.webp", main:["frank","emz","gale","janet","bull"], info:[""] },
    "barley": { img:"images/barley.webp", main:["tick","mortis","brock","edgar","kenji","kaze","mico"], info:[""] },
    "bea": { img:"images/bea.webp", main:["charlie","tick","sprout","grom","mrp","byron","mandy"], info:[""] },
    "belle": { img:"images/belle.webp", main:["piper","meg","leon","mandy","byron","kit","lily"], info:[""] },
    "berry": { img:"images/berry.webp", main:["kaze","crow","barley","stu","kenji","kit","mortis"], info:[""] },
    "bibi": { img:"images/bibi.webp", main:["mortis","jacky","stu","surge","griff","cord","primo","tara","bull"], info:[""] },
    "bo": { img:"images/bo.webp", main:["max","piper","colt","stu","mico","mrp"], info:[""] },
    "bolt": { img:"images/bolt.webp", main:[,], info:[""] },
    "bonnie": { img:"images/bonnie.webp", main:["charlie","colette","bea","pam","piper","rt","gus","tara"], info:[""] },
    "brock": { img:"images/brock.webp", main:["piper","rt","max","darryl","mortis","mandy","nani","kaze"], info:[""] },
    "bull": { img:"images/bull.webp", main:["charlie","griff","shelly","emz","gale","cord","mina","otis","nita"], info:[""] },
    "buster": { img:"images/buster.webp", main:["bull","mina","rt","ash","darryl","belle"], info:[""] },
    "buzz": { img:"images/buzz.webp", main:["charlie","griff","stu","max","sandy","mina","cord","bull","surge","bibi","frank","ash"], info:[""] },
    "byron": { img:"images/byron.webp", main:["piper","crow","bea","ash"], info:[""] },
    "carl": { img:"images/carl.webp", main:["buzz","jacky","surge","colette","stu","mina","bull","cord","bibi"], info:[""] },
    "charlie": { img:"images/charlie.webp", main:["amber","sandy","janet","juju"], info:[""] },
    "chester": { img:"images/chester.webp", main:["pearl","amber","charlie","lumi","mina","stu"], info:[""] },
    "chuck": { img:"images/chuck.webp", main:["charlie","crow","cord","mina","bull","kaze"], info:[""] },
    "clancy": { img:"images/clancy.webp", main:["mrp","charlie","tara","bea","piper","byron"], info:[""] },
    "colette": { img:"images/colette.webp", main:["tick","griff","bea","poco","charlie","belle","gus","lumi"], info:[""] },
    "colt": { img:"images/colt.webp", main:["buster","darryl","mortis","spike","piper","bonnie","belle","gus","byron"], info:[""] },
    "cord": { img:"images/cord.webp", main:["charlie","mina","frank","sandy","buster","surge","gale","nita"], info:[""] },
    "crow": { img:"images/crow.webp", main:["piper","charlie","janet","spike","lola","bea","pearl","hank"], info:[""] },
    "damian": { img:"images/damian.webp", main:["emz","sirius","surge","lou"], info:[""] },
    "darryl": { img:"images/darryl.webp", main:["lou","surge","bea","ruffs","mina","cord","shelly","griff","rt"], info:[""] },
    "doug": { img:"images/doug.webp", main:["crow","cord","lumi","bea","griff","frank","lily"], info:[""] },
    "draco": { img:"images/draco.webp", main:["lumi","amber","pam","lou","mina","cord","frank","ash","kit"], info:[""] },
    "dyna": { img:"images/dyna.webp", main:["mortis","bibi","stu","kenji","mico","kit","kaze","hank"], info:[""] },
    "edgar": { img:"images/edgar.webp", main:["gale","otis","stu","shelly","hank","bull","doug","jacky","cord","poco"], info:[""] },
    "primo": { img:"images/primo.webp", main:["stu","surge","colette","gale","cord","mina","griff","shelly","charlie"], info:[""] },
    "emz": { img:"images/emz.webp", main:["mortis","stu","crow","janet","bonnie","amber"], info:[""] },
    "eve": { img:"images/eve.webp", main:["alli","carl","janet","poco"], info:[""] },
    "fang": { img:"images/fang.webp", main:["charlie","otis","gale","gene","eve","rt","chester","tara","draco"], info:[""] },
    "finx": { img:"images/finx.webp", main:["emz","meeple","kenji","rosa","bull","shade","bibi","mortis","larry"], info:[""] },
    "frank": { img:"images/frank.webp", main:["colette","surge","primo","charlie","chester","lou","sandy"], info:[""] },
    "gale": { img:"images/gale.webp", main:["mico","buzz","spike","piper","belle","amber","janet","larry","juju","cord"], info:[""] },
    "gene": { img:"images/gene.webp", main:["8bit","mrp","eve","penny","charlie","tara","belle"], info:[""] },
    "gigi": { img:"images/gigi.webp", main:["shelly","fang","otis","cord","edgar"], info:[""] },
    "glowbert": { img:"images/glowbert.webp", main:["crow","kenji","belle","jessie"], info:[""] },
    "gray": { img:"images/gray.webp", main:["gene","tick","mortis","leon","crow","fang","max"], info:[""] },
    "griff": { img:"images/griff.webp", main:[,"crow","spike","bea","janet","stu","mina"], info:[""] },
    "grom": { img:"images/grom.webp", main:["lily","mico","mortis","fang","darryl","kenji","kit","kaze"], info:[""] },
    "gus": { img:"images/gus.webp", main:["charlie","bo","byron","mandy","piper","eve","darryl","janet","8bit"], info:[""] },
    "hank": { img:"images/hank.webp", main:["willow","larry","frank","dyna","mina","bull","draco","bibi"], info:[""] },
    "jacky": { img:"images/jacky.webp", main:["griff","emz","crow","otis","shelly","surge","gale","frank","bull","primo","draco"], info:[""] },
    "jaeyong": { img:"images/jaeyong.webp", main:["griff","bo","charlie","crow","kenji"], info:[""] },
    "janet": { img:"images/janet.webp", main:["kenji","griff","bonnie","amber","carl","frank","darryl","gus"], info:[""] },
    "jessie": { img:"images/jessie.webp", main:[,"piper","barley","larry","squeak"], info:[""] },
    "juju": { img:"images/juju.webp", main:["barley","kaze","shade","frank","brock","cord","kit","tick"], info:[""] },
    "kenji": { img:"images/kenji.webp", main:["pam","bull","frank","draco","cord","mina","lou","meeple","jaeyong","hank"], info:[""] },
    "kaze": { img:"images/kaze.webp", main:["crow","bull","rt","otis","griff","stu"], info:[""] },
    "kit": { img:"images/kit.webp", main:["cord","rt","frank","hank","ollie","lily","draco"], info:[""] },
    "larry": { img:"images/larry.webp", main:["mico","edgar","mortis","kenji","willow"], info:[""] },
    "leon": { img:"images/leon.webp", main:["crow","pearl","gene","pam","jaeyong","mina","janet","charlie"], info:[""] },
    "lily": { img:"images/lily.webp", main:["buzz","cord","bull","draco","rt","pearl","8bit","doug"], info:[""] },
    "lola": { img:"images/lola.webp", main:["belle","bo","penny","amber","carl","lumi"], info:[""] },
    "lou": { img:"images/lou.webp", main:["hank","janet","carl","max","poco","gus","byron","bea","kenji"], info:[""] },
    "lumi": { img:"images/lumi.webp", main:["amber","draco","piper","mandy","belle","gene","lola"], info:[""] },
    "maisie": { img:"images/maisie.webp", main:["stu","charlie","mina","larry","juju"], info:[""] },
	"mandy": { img:"images/mandy.webp", main:["",""], info:[""] },
    "max": { img:"images/max.webp", main:["crow","lola","poco","gus","jaeyong"], info:[""] },
    "meg": { img:"images/meg.webp", main:["draco","spike","bea","lola","buster"], info:[""] },
    "melodie": { img:"images/melodie.webp", main:["amber","buzz","draco","crow","belle"], info:[""] },
    "meeple": { img:"images/meeple.webp", main:["max","kenji","mortis","mico","frank","bull","mrp","penny"], info:[""] },
    "mico": { img:"images/mico.webp", main:["gale","buzz","mortis","fang","darryl","kenji","kit","kaze","edgar"], info:[""] },
    "mina": { img:"images/mina.webp", main:["bull","frank","cord","surge","griff","buster","ash","jacky"], info:[""] },
    "moe": { img:"images/moe.webp", main:["spike","sprout","tick","grom","barley","willow"], info:[""] },
    "mortis": { img:"images/mortis.webp", main:["jacky","stu","shelly","otis","bull","mina","griff","chester"], info:[""] },
    "mrp": { img:"images/mrp.webp", main:["kit","sprout","janet","amber","carl","darryl","edgar","kenji","kaze"], info:[""] },
    "najia": { img:"images/najia.webp", main:["byron","kenji","mortis","poco","bibi"], info:[""] },
    "nani": { img:"images/nani.webp", main:["gene","leon","tick","max","sprout","darryl"], info:[""] },
    "nita": { img:"images/nita.webp", main:["barley","carl","griff","amber","cord","sandy"], info:[""] },
    "nori": { img:"images/nori.webp", main:[,], info:[""] },
    "ollie": { img:"images/ollie.webp", main:["poco","maisie","surge","griff","lou","colette"], info:[""] },
    "otis": { img:"images/otis.webp", main:["juju","larry","piper","byron","tick","amber","janet","stu"], info:[""] },
    "pam": { img:"images/pam.webp", main:["crow","squeak","spike","lou","8bit","charlie","draco","amber","stu"], info:[""] },
    "pearl": { img:"images/pearl.webp", main:["chester","leon","amber","crow","spike","lola","meg"], info:[""] },
    "penny": { img:"images/penny.webp", main:["belle","grom","amber","squeak","juju","larry","kenji"], info:[""] },
    "pierce": { img:"images/pierce.webp", main:["ruffs","mortis","charlie","tara","spike"], info:[""] },
    "piper": { img:"images/piper.webp", main:["nani","max","leon","tick","gene","kit","kaze"], info:[""] },
    "poco": { img:"images/poco.webp", main:["sam","crow","griff","mortis","emz","kit","kaze","kenji","lou","edgar"], info:[""] },
    "rt": { img:"images/rt.webp", main:["piper","brock","max","leon","mortis","darryl","crow"], info:[""] },
    "rico": { img:"images/rico.webp", main:["brock","ruffs","sprout","grom","buzz","stu","dyna","larry"], info:[""] },
    "rosa": { img:"images/rosa.webp", main:["shelly","gale","frank","primo","bull","amber"], info:[""] },
    "ruffs": { img:"images/ruffs.webp", main:["buzz","sprout","carl","belle"], info:[""] },
    "sam": { img:"images/sam.webp", main:["gale","griff","surge","cord","charlie","nita","janet","draco","stu"], info:[""] },
    "sandy": { img:"images/sandy.webp", main:["crow","nita","gene","poco","cord"], info:[""] },
    "shade": { img:"images/shade.webp", main:["frank","jacky","doug","lou","bull","hank","trunk","brock"], info:[""] },
    "shelly": { img:"images/shelly.webp", main:["chester","cord","stu","crow","emz","tara","nita","amber"], info:[""] },
    "sirius": { img:"images/sirius.webp", main:["buzz","penny","mortis","pierce"], info:[""] },
    "spike": { img:"images/spike.webp", main:["moe","sprout","tick","grom","carl","piper","larry","juju"], info:[""] },
    "sprout": { img:"images/sprout.webp", main:["mico","tick","mortis","darryl","buzz","kaze","kenji","edgar"], info:[""] },
    "squeak": { img:"images/squeak.webp", main:["darryl","kenji","mortis","max","leon","buzz","kaze"], info:[""] },
    "starrnova": { img:"images/starrnova.webp", main:[], info:[""] },
    "stu": { img:"images/stu.webp", main:["charlie","amber","crow","lola","poco","ruffs","tara","pam","sam"], info:[""] },
    "surge": { img:"images/surge.webp", main:["mrp","ruffs","spike","eve","tara","charlie","larry","juju","stu","ash"], info:[""] },
    "tara": { img:"images/tara.webp", main:["willow","emz","janet","poco","amber","sandy","juju","larry"], info:[""] },
    "tick": { img:"images/tick.webp", main:["mandy","gene","fang","sam","kenji","kit","mortis","kaze","darryl"], info:[""] },
    "trunk": { img:"images/trunk.webp", main:["lou","spike","amber","maisie"], info:[""] },
    "willow": { img:"images/willow.webp", main:["tick","barley","larry","juju","stu","buzz"], info:[""] },
    "ziggy": { img:"images/ziggy.webp", main:["stu","mortis","gray","bibi","tick","hank"], info:[""] }
};

/* =========================
   GROUP CLASSES
========================= */
const classGroups = {
    "thrower": ["barley","dyna","larry","tick","sprout","grom","ziggy","sirius","juju","willow","berry"],
    "tank": ["trunk","draco","frank","buster","primo","hank","jacky","rosa","ash","damian","bibi","bull"],
    "assassin": ["ollie","kenji","mortis","shade","mina","buzz","alli","carl","edgar","kaze","lily","mico","sam","chuck","gigi","melodie","darryl","bolt","nori","fang","starrnova"],
    "antitank": ["chester","nita","moe","rico","tara","emz","lou","finx","ruffs","otis","lumi","shelly","surge","charlie","gale","spike","cord","maisie","colt","griff","crow","8bit","clancy","colette","meg"],
    "support": ["kit","max","gray","poco","jaeyong","doug","glowbert"],
    "sniper": ["mandy","rt","gus","piper","brock","byron","angelo","pierce","nani","belle","bea"],
    "control": ["amber","meeple","leon","pam","bo","pearl","gene","stu","janet","penny","jessie","sandy","squeak","eve","lola","najia","bonnie","mrp"]
};

const brawlerClass = {};
	for (const cls in classGroups) {
		classGroups[cls].forEach(name => {
			brawlerClass[name] = cls;
		});
}

/* =========================
   CLASS ORDER (for sort toggle)
========================= */
const classOrder = [
    "assassin",
	"tank",
	"antitank",
    "sniper",
    "thrower",
    "control",
    "support"
];